Repository gemini-hlsw/lucuma-ui, pull requests merged in 2023-08, with the labels that each got.

#894 Bump lucuma-react
  build.sbt
  modules/demo/src/main/scala/lucuma/ui/demo/Demo.scala
  modules/ui/src/main/scala/lucuma/ui/components/About.scala
  modules/ui/src/main/scala/lucuma/ui/components/CopyControl.scala
  modules/ui/src/main/scala/lucuma/ui/components/LoginIcons.scala
  modules/ui/src/main/scala/lucuma/ui/components/LoginStyles.scala
  modules/ui/src/main/scala/lucuma/ui/components/Logo.scala
  modules/ui/src/main/scala/lucuma/ui/components/MoonPhase.scala
  modules/ui/src/main/scala/lucuma/ui/components/SolarProgress.scala
  modules/ui/src/main/scala/lucuma/ui/components/UserSelectionForm.scala
  modules/ui/src/main/scala/lucuma/ui/components/state/ConnectionManager.scala
  modules/ui/src/main/scala/lucuma/ui/components/state/IfLogged.scala
  modules/ui/src/main/scala/lucuma/ui/components/state/LogoutTracker.scala
  modules/ui/src/main/scala/lucuma/ui/components/state/SSOManager.scala
  modules/ui/src/main/scala/lucuma/ui/enums/Theme.scala
  modules/ui/src/main/scala/lucuma/ui/package.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/BooleanRadioButtons.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/CheckboxView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/EnumDropdown.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/EnumDropdownOptionalView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/EnumDropdownView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/EnumOptionalDropdown.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormDropdown.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormDropdownOptional.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormEnumDropdownOptionalView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormEnumDropdownView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormInputText.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormInputTextArea.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormInputTextAreaView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormInputTextView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/FormLabel.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/LucumaPrimeStyles.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/RadioButtonView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/SelectButtonEnumView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/SliderView.scala
  modules/ui/src/main/scala/lucuma/ui/primereact/primereact.scala
  modules/ui/src/main/scala/lucuma/ui/reusability/package.scala
  modules/ui/src/main/scala/lucuma/ui/syntax/components.scala
  modules/ui/src/main/scala/lucuma/ui/syntax/css.scala
  modules/ui/src/main/scala/lucuma/ui/syntax/mod.scala
  modules/ui/src/main/scala/lucuma/ui/syntax/util.scala
  modules/ui/src/main/scala/lucuma/ui/table/ColumnSelector.scala
  modules/ui/src/main/scala/lucuma/ui/table/PrimeTable.scala
  modules/ui/src/main/scala/lucuma/ui/table/TableIcons.scala
  modules/web/server/buildinfo.properties
Labels: demo, ui

#899 Unified sequence table row model extracted from explore and observe
  build.sbt
  modules/ui/src/main/scala/lucuma/ui/reusability/package.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/SequenceRow.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/SequenceRowFormatters.scala
Labels: ui

#902 useDynTable hook and organize table hooks
  build.sbt
  modules/ui/src/main/scala/lucuma/ui/reusability/package.scala
  modules/ui/src/main/scala/lucuma/ui/table/hooks/DynTable.scala
  modules/ui/src/main/scala/lucuma/ui/table/hooks/TableStateStore.scala
  modules/ui/src/main/scala/lucuma/ui/table/hooks/UseDynTable.scala
  modules/ui/src/main/scala/lucuma/ui/table/hooks/UseReactTableWithStateStore.scala
  modules/ui/src/main/scala/lucuma/ui/table/hooks/package.scala
Labels: ui

#911 Migrate icons component
  build.sbt
  modules/ui/src/main/scala/lucuma/ui/components/LoginIcons.scala
  modules/ui/src/main/scala/lucuma/ui/table/TableIcons.scala
Labels: ui

#915 Migrate demo to vite
  build.sbt
  modules/demo/package.json
  modules/demo/src/main/resources/app.js
  modules/demo/src/main/resources/dev.js
  modules/demo/src/main/resources/styles.css
  modules/demo/src/main/webapp/index.html
  modules/demo/src/main/webapp/main.jsx
  modules/demo/src/main/webapp/styles.css
  modules/demo/vite.config.js
  modules/demo/yarn.lock
  project/plugins.sbt
Labels: demo

#917 Migrate sequence table columns from explore
  build.sbt
  modules/demo/.npmrc
  modules/demo/package.json
  modules/demo/src/main/scala/lucuma/ui/demo/Demo.scala
  modules/demo/src/main/scala/lucuma/ui/demo/FormComponent.scala
  modules/demo/src/main/scala/lucuma/ui/demo/IconsDemo.scala
  modules/demo/src/main/webapp/main.jsx
  modules/demo/src/main/webapp/styles.scss
  modules/demo/vite.config.js
  modules/demo/yarn.lock
  modules/ui/src/main/resources/lucuma-css/lucuma-ui-sequence.scss
  modules/ui/src/main/scala/lucuma/ui/primereact/SelectButtonEnumView.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/SequenceColumns.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/SequenceIcons.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/SequenceRow.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/SequenceStyles.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/StepTypeDisplay.scala
  modules/ui/src/main/scala/lucuma/ui/sequence/package.scala
Labels: demo, ui

#910 Export SideTabs component
  modules/ui/src/main/resources/lucuma-css/side-tabs.scss
  modules/ui/src/main/scala/lucuma/ui/components/SideTabs.scala
Labels: ui
